
train_transform:
  resize_height: 500
  resize_width: 375
  normalize_mean: [0.4914, 0.4822, 0.4465]
  normalize_std: [0.2023, 0.1994, 0.2010]
test_transform:
  resize_height: 500
  resize_width: 375
  normalize_mean: [0.4914, 0.4822, 0.4465]
  normalize_std: [0.2023, 0.1994, 0.2010]
data_module:
  batch_size: 64
  seed: 42
  fraction_train: 0.8
  small_subset: False
  num_samples: None

