
train_transform:
  resize_height: 500
  resize_width: 375
  normalize_mean: [0.5]
  normalize_std: [0.5]
test_transform:
  resize_height: 500
  resize_width: 375
  normalize_mean: [0.5]
  normalize_std: [0.5]
data_module:
  batch_size: 64
  seed: 42
  fraction_train: 0.8

